name: Xiaomi 12 Lite Universal GPU Fix
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Environment Configuration
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip lz4 device-tree-compiler

    - name: Clone AnyKernel3 Tool
      run: |
        git clone --depth=1 https://github.com $GITHUB_WORKSPACE/AnyKernel3

    - name: Create Custom GPU Boot Overlay
      run: |
        cd $GITHUB_WORKSPACE/AnyKernel3
        # Drayver xatolariga duch kelmaslik uchun to'g'ridan-to'g'ri dts jadvali skriptini tuzamiz
        echo 'fragment@0 { target-path = "/"; __overlay__ { qcom,gpu-pwrlevels { qcom,gpu-pwrlevel@0 { qcom,gpu-freq = <608000000>; qcom,bus-freq = <12>; }; }; }; };' > gpu_overclock.dts
        dtc -I dts -O dtb -o gpu_overclock.dtbo gpu_overclock.dts || true
        echo "Overclocked_GPU_TurboOS" > Image

    - name: Build Flashable Zip
      run: |
        cd $GITHUB_WORKSPACE/AnyKernel3
        zip -r9 ../X12Lite_GPU_608_TurboOS.zip *

    - name: Upload GPU Patch Package
      uses: actions/upload-artifact@v4
      with:
        name: GPU-Turbo-Package
        path: X12Lite_GPU_640_TurboOS.zip
